version: '3.8'

services:
  app:
    build: .
    container_name: trucknstyle_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=!blaograna27!
      - DB_NAME=truckn_style_bdd
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: mysql:8.0
    container_name: trucknstyle_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: truckn_style_bdd
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: trucknstyle_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data:
